'use client'

import { useEffect, useMemo, useState } from 'react'
import { Copy, Check, Plus, Globe2, Trash2, RefreshCw, Link2, Cloud, ShieldCheck, ExternalLink, X, RadioTower } from 'lucide-react'
import { useWorkspaceStore } from '@/store/workspace'
import { H, PageHeader, Panel, StatusPill, Empty } from '@/components/hawk/ui'

type DomainPayload = { domains:any[]; pages:any[]; rules:any[]; cloudflare:{configured:boolean;cnameTarget:string|null} }

function cleanHost(v:string){return v.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0]}
function shortDate(v?:string|null){if(!v)return '—';return new Date(v).toLocaleString('pt-BR')}

export default function DomainsPage(){
  const {active}=useWorkspaceStore()
  const [data,setData]=useState<DomainPayload>({domains:[],pages:[],rules:[],cloudflare:{configured:false,cnameTarget:null}})
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [show,setShow]=useState(false); const [selected,setSelected]=useState<any|null>(null); const [copied,setCopied]=useState(''); const [busy,setBusy]=useState('')
  const [form,setForm]=useState<any>({hostname:'',origin_type:'page',page_id:'',external_origin_url:'',rule_id:'',path_prefix:'/',inject_tracker:true})

  async function load(){if(!active?.id)return;setLoading(true);setError('');try{const r=await fetch(`/api/domains?workspace_id=${encodeURIComponent(active.id)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao carregar domínios');setData(j);setSelected((cur:any)=>cur?(j.domains?.find((d:any)=>d.id===cur.id)||cur):null);if(!form.page_id&&j.pages?.[0])setForm((f:any)=>({...f,page_id:j.pages[0].id}))}catch(e){setError(e instanceof Error?e.message:'Erro')}finally{setLoading(false)}}
  useEffect(()=>{load()},[active?.id])

  const totals=useMemo(()=>({active:data.domains.filter(d=>d.status==='active').length,pending:data.domains.filter(d=>d.status!=='active').length}),[data.domains])

  async function create(){if(!active?.id)return;setBusy('create');setError('');try{const r=await fetch('/api/domains',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:active.id,...form,hostname:cleanHost(form.hostname)})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao cadastrar');setShow(false);setForm({hostname:'',origin_type:'page',page_id:data.pages?.[0]?.id||'',external_origin_url:'',rule_id:'',path_prefix:'/',inject_tracker:true});await load();const created=(await (await fetch(`/api/domains?workspace_id=${encodeURIComponent(active.id)}`,{cache:'no-store'})).json()).domains?.find((d:any)=>d.hostname===cleanHost(form.hostname));if(created)setSelected(created)}catch(e){setError(e instanceof Error?e.message:'Erro')}finally{setBusy('')}}
  async function verify(d:any){if(!active?.id)return;setBusy(`verify:${d.id}`);setError('');try{const r=await fetch(`/api/domains/${d.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:active.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao verificar');await load()}catch(e){setError(e instanceof Error?e.message:'Erro')}finally{setBusy('')}}
  async function remove(d:any){if(!active?.id||!confirm(`Remover ${d.hostname}?`))return;setBusy(`del:${d.id}`);try{const r=await fetch(`/api/domains/${d.id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:active.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha');if(selected?.id===d.id)setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Erro')}finally{setBusy('')}}
  async function copy(k:string,v:string){await navigator.clipboard.writeText(v);setCopied(k);setTimeout(()=>setCopied(''),1200)}

  return <div className="shell-page">
    <PageHeader title="Domínios" sub="Conecte um hostname a uma Page ou origem externa. O Edge resolve tudo pelo domínio e pela rota." right={<><button className="tt-icon-btn" onClick={load}><RefreshCw size={14}/></button><button className="tt-btn tt-btn-primary" onClick={()=>setShow(true)}><Plus size={14}/> Adicionar domínio</button></>}/>

    <div className="tt-grid-3" style={{marginBottom:14}}><Panel style={{padding:16}}><div className="tt-cap">Domínios</div><div className="tt-num" style={{fontSize:28,marginTop:6}}>{loading?'—':data.domains.length}</div></Panel><Panel style={{padding:16}}><div className="tt-cap">Ativos</div><div className="tt-num" style={{fontSize:28,marginTop:6,color:H.green}}>{loading?'—':totals.active}</div></Panel><Panel style={{padding:16}}><div className="tt-cap">Aguardando</div><div className="tt-num" style={{fontSize:28,marginTop:6,color:H.amber}}>{loading?'—':totals.pending}</div></Panel></div>
    {error&&<Panel style={{padding:14,marginBottom:14,borderColor:'rgba(240,137,155,.25)'}}><div style={{color:H.red,fontSize:12}}>{error}</div></Panel>}

    <Panel>
      <div style={{padding:18}}>
        {data.domains.length===0&&!loading?<Empty pad={42}>Nenhum domínio cadastrado. Adicione um hostname e ligue a uma Page.</Empty>:data.domains.map(d=>{const route=d.routes?.[0];const page=data.pages.find(p=>p.id===route?.page_id);const rule=data.rules.find(r=>r.id===route?.rule_id);return <div key={d.id} style={{display:'grid',gridTemplateColumns:'minmax(210px,1.4fr) minmax(180px,1fr) minmax(160px,.8fr) auto',gap:14,alignItems:'center',padding:'14px 0',borderBottom:`1px solid ${H.lineSoft}`}}>
          <button onClick={()=>setSelected(d)} style={{textAlign:'left',minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:36,height:36,borderRadius:11,display:'grid',placeItems:'center',background:'rgba(163,167,242,.10)'}}><Globe2 size={16} color={H.lav}/></div><div style={{minWidth:0}}><div className="tt-mono" style={{color:H.text,fontSize:13,fontWeight:700,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{d.hostname}</div><div className="tt-cap" style={{marginTop:3}}>DNS {d.dns_status||'pending'} · SSL {d.ssl_status||'pending'}</div></div></div></button>
          <div><div className="tt-cap">Destino</div><div style={{color:H.text,fontSize:12,fontWeight:700,marginTop:4,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{route?.origin_type==='page'?page?.name||'Page removida':route?.external_origin_url||'—'}</div></div>
          <div><div className="tt-cap">Regra</div><div style={{color:H.sub,fontSize:12,marginTop:4}}>{rule?.name||'Regra padrão'}</div></div>
          <div style={{display:'flex',alignItems:'center',gap:8}}><StatusPill tone={d.status==='active'?'good':d.status==='error'?'bad':'warn'}>{d.status}</StatusPill><button className="tt-icon-btn" title="Detalhes" onClick={()=>setSelected(d)}><ExternalLink size={13}/></button><button className="tt-icon-btn" title="Remover" disabled={busy===`del:${d.id}`} onClick={()=>remove(d)}><Trash2 size={13}/></button></div>
        </div>})}
      </div>
    </Panel>

    {show&&<div style={{position:'fixed',inset:0,zIndex:100,background:'rgba(5,7,14,.72)',backdropFilter:'blur(8px)',display:'grid',placeItems:'center',padding:18}} onMouseDown={()=>setShow(false)}><Panel style={{width:'min(720px,100%)',maxHeight:'92vh',overflow:'auto'}}><div style={{padding:20}} onMouseDown={e=>e.stopPropagation()}>
      <div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><h2 className="tt-h" style={{fontSize:20}}>Adicionar domínio</h2><div className="tt-cap" style={{marginTop:4}}>O mesmo Edge poderá atender vários domínios, cada um com sua rota.</div></div><button className="tt-icon-btn" onClick={()=>setShow(false)}><X size={14}/></button></div>
      <div style={{marginTop:18}}><label className="tt-cap">Hostname</label><input className="tt-input" style={{marginTop:8}} value={form.hostname} onChange={e=>setForm({...form,hostname:e.target.value})} placeholder="go.seudominio.com"/></div>
      <div style={{marginTop:16}}><label className="tt-cap">Destino</label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{[['page','Tiotrack Page',Cloud],['external','URL externa',Link2]].map(([key,label,Icon]:any)=><button key={key} onClick={()=>setForm({...form,origin_type:key})} className="tt-inset" style={{padding:14,textAlign:'left',borderColor:form.origin_type===key?'rgba(163,167,242,.4)':undefined}}><Icon size={17} color={form.origin_type===key?H.lavLight:H.sub}/><div style={{color:H.text,fontWeight:800,marginTop:8}}>{label}</div></button>)}</div></div>
      {form.origin_type==='page'?<div style={{marginTop:14}}><label className="tt-cap">Page</label><select className="tt-select" style={{marginTop:8}} value={form.page_id} onChange={e=>setForm({...form,page_id:e.target.value})}><option value="">Selecione...</option>{data.pages.map(p=><option value={p.id} key={p.id}>{p.name} {p.status!=='online'?'(não publicada)':''}</option>)}</select>{data.pages.length===0&&<div className="tt-cap" style={{marginTop:6,color:H.amber}}>Você ainda não criou uma Page.</div>}</div>:<div style={{marginTop:14}}><label className="tt-cap">Origem externa</label><input className="tt-input" style={{marginTop:8}} value={form.external_origin_url} onChange={e=>setForm({...form,external_origin_url:e.target.value})} placeholder="https://projeto.vercel.app"/></div>}
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:14}}><div><label className="tt-cap">Path</label><input className="tt-input" style={{marginTop:8}} value={form.path_prefix} onChange={e=>setForm({...form,path_prefix:e.target.value})}/></div><div><label className="tt-cap">Regra de tráfego</label><select className="tt-select" style={{marginTop:8}} value={form.rule_id} onChange={e=>setForm({...form,rule_id:e.target.value})}><option value="">Regra padrão do workspace</option>{data.rules.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div></div>
      <button className="tt-inset" onClick={()=>setForm({...form,inject_tracker:!form.inject_tracker})} style={{width:'100%',padding:13,display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:14,textAlign:'left'}}><div><div style={{color:H.text,fontWeight:700,fontSize:12}}>Tracking automático</div><div className="tt-cap" style={{marginTop:3}}>Injeta tiotrack.js em HTML servido pelo Edge.</div></div><div style={{width:36,height:21,borderRadius:99,padding:2,background:form.inject_tracker?H.lav:'rgba(163,167,242,.12)'}}><div style={{width:17,height:17,borderRadius:99,background:form.inject_tracker?'#11142a':H.muted,transform:`translateX(${form.inject_tracker?15:0}px)`}}/></div></button>
      <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:20,paddingTop:16,borderTop:`1px solid ${H.line}`}}><button className="tt-btn" onClick={()=>setShow(false)}>Cancelar</button><button className="tt-btn tt-btn-primary" disabled={busy==='create'||!form.hostname|| (form.origin_type==='page'&&!form.page_id) || (form.origin_type==='external'&&!form.external_origin_url)} onClick={create}>{busy==='create'?'Cadastrando...':'Cadastrar domínio'}</button></div>
    </div></Panel></div>}

    {selected&&<div style={{position:'fixed',inset:0,zIndex:101,background:'rgba(5,7,14,.72)',backdropFilter:'blur(8px)',display:'grid',placeItems:'center',padding:18}} onMouseDown={()=>setSelected(null)}><Panel style={{width:'min(760px,100%)',maxHeight:'92vh',overflow:'auto'}}><div style={{padding:20}} onMouseDown={e=>e.stopPropagation()}>
      <div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="tt-eyebrow"><RadioTower size={12}/> Configuração DNS</div><h2 className="tt-h" style={{fontSize:20,marginTop:6}}>{selected.hostname}</h2></div><button className="tt-icon-btn" onClick={()=>setSelected(null)}><X size={14}/></button></div>
      <div className="tt-inset" style={{padding:14,marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div style={{color:H.text,fontWeight:800,fontSize:13}}>1. Aponte o domínio para o Edge</div><div className="tt-cap" style={{marginTop:4}}>Crie este registro no provedor de DNS.</div></div><StatusPill tone={selected.dns_status==='verified'?'good':'warn'}>{selected.dns_status||'pending'}</StatusPill></div>
        <DnsRow label="TIPO" value="CNAME" copy={()=>copy('type','CNAME')} copied={copied==='type'}/><DnsRow label="NOME" value={selected.hostname} copy={()=>copy('name',selected.hostname)} copied={copied==='name'}/><DnsRow label="DESTINO" value={selected.cname_target||data.cloudflare.cnameTarget||'Configure TIO_EDGE_CNAME_TARGET'} copy={()=>copy('target',selected.cname_target||data.cloudflare.cnameTarget||'')} copied={copied==='target'}/>
      </div>
      {selected.cf_validation?.ownership_verification&&<div className="tt-inset" style={{padding:14,marginTop:12}}><div style={{color:H.text,fontWeight:800,fontSize:13}}>2. Validação de propriedade</div><div className="tt-cap" style={{marginTop:4}}>Cloudflare pode solicitar um TXT adicional antes de ativar o hostname.</div><DnsRow label="TIPO" value={String(selected.cf_validation.ownership_verification.type||'TXT').toUpperCase()}/><DnsRow label="NOME" value={selected.cf_validation.ownership_verification.name||'—'} copy={()=>copy('ownname',selected.cf_validation.ownership_verification.name||'')} copied={copied==='ownname'}/><DnsRow label="VALOR" value={selected.cf_validation.ownership_verification.value||'—'} copy={()=>copy('ownvalue',selected.cf_validation.ownership_verification.value||'')} copied={copied==='ownvalue'}/></div>}
      {(selected.cf_validation?.ssl_validation_records||[]).map((v:any,i:number)=><div key={i} className="tt-inset" style={{padding:14,marginTop:12}}><div style={{color:H.text,fontWeight:800,fontSize:13}}>SSL / DCV</div><DnsRow label="TIPO" value={v.txt_name?'TXT':'CNAME'}/><DnsRow label="NOME" value={v.txt_name||v.cname||'—'} copy={()=>copy(`ssl-n-${i}`,v.txt_name||v.cname||'')} copied={copied===`ssl-n-${i}`}/><DnsRow label="VALOR" value={v.txt_value||v.cname_target||'—'} copy={()=>copy(`ssl-v-${i}`,v.txt_value||v.cname_target||'')} copied={copied===`ssl-v-${i}`}/></div>)}
      <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:12}}><div className="tt-inset" style={{padding:12}}><div className="tt-cap">Cloudflare</div><div style={{marginTop:5,color:H.text,fontWeight:700,fontSize:12}}>{selected.cf_status||'não configurado'}</div></div><div className="tt-inset" style={{padding:12}}><div className="tt-cap">SSL</div><div style={{marginTop:5,color:H.text,fontWeight:700,fontSize:12}}>{selected.cf_ssl_status||selected.ssl_status||'pending'}</div></div><div className="tt-inset" style={{padding:12}}><div className="tt-cap">Edge sync</div><div style={{marginTop:5,color:H.text,fontWeight:700,fontSize:12}}>{selected.edge_synced_at?'sincronizado':'aguardando'}</div></div></div>
      {selected.cf_error&&<div style={{color:H.red,fontSize:12,marginTop:12}}>{selected.cf_error}</div>}
      <div className="tt-cap" style={{marginTop:12}}>Última verificação: {shortDate(selected.dns_last_checked_at)}</div>
      <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18,paddingTop:16,borderTop:`1px solid ${H.line}`}}><button className="tt-btn" onClick={()=>setSelected(null)}>Fechar</button><button className="tt-btn tt-btn-primary" disabled={busy===`verify:${selected.id}`||!data.cloudflare.configured} onClick={()=>verify(selected)}><RefreshCw size={13}/>{busy===`verify:${selected.id}`?'Verificando...':'Verificar agora'}</button></div>
      {!data.cloudflare.configured&&<div className="tt-cap" style={{marginTop:8,color:H.amber,textAlign:'right'}}>Para verificação automática, configure CLOUDFLARE_SAAS_ZONE_ID e o token no ambiente.</div>}
    </div></Panel></div>}
  </div>
}

function DnsRow({label,value,copy,copied}:{label:string;value:string;copy?:()=>void;copied?:boolean}){return <div style={{display:'grid',gridTemplateColumns:'86px 1fr auto',gap:10,alignItems:'center',marginTop:10}}><span className="tt-cap">{label}</span><code className="tt-mono" style={{fontSize:11,color:H.lavLight,wordBreak:'break-all'}}>{value}</code>{copy?<button className="tt-icon-btn" onClick={copy}>{copied?<Check size={12} color={H.green}/>:<Copy size={12}/>}</button>:<span/>}</div>}
